version: '3.8'

services:
  # ASP.Net'in yapılandırması
  fintrackwebapi:
    build:
      context: ./FinTrackWebApi
      dockerfile: Dockerfile
    container_name: fintrack_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FinBotApiUrl=http://finbotwebapi:8000
      - ConnectionStrings__DefaultConnection=Host=db_postgres;Port=5432;Database=myfintrackdb;Username=postgres;Password=140xxx-+
    depends_on:
      - finbotwebapi
      - db_postgres
    networks:
      - fintrac_network

  # Ngrok 'un' yapılandırması
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
       - NGROK_AUTHTOKEN=2wuCJxMriYB0MvVAanMEzZwsVGK_3UfHpEqo3wyQ73BGuRGYX
    command:
      - "http"
      - "fintrack_api:8080"
      - "--log=stdout"
    depends_on:
      - fintrackwebapi
    networks:
      - fintrac_network

  # FinBot yapılandırması
  finbotwebapi:
    build:
      context: ./FinBotWebApi
      dockerfile: Dockerfile
    container_name: finbot_api
    ports:
      - "5001:8000"
    env_file:
      - ./FinBotWebApi/.env
    networks:
      - fintrac_network

  # Veritabanının yapılandırması
  db_postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=myfintrackdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=140xxx-+
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintrac_network
    restart: unless-stopped

networks:
  fintrac_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local