name: Format Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check formatting
        # <-- DEĞİŞİKLİK BURADA
        # Projenizin .sln dosyasının adını --workspace parametresi ile belirtiyoruz.
        run: dotnet format --workspace FinTrackWebApi.sln --verify-no-changes